### PR TITLE
TidalCycles banner logo

### PR DESCRIPTION
**Pull request by nullish**
Changing the main image on the banner to mono TidalCycles creative from photo. @heavy-lifting You can preview this at [my test site](http://tidalclub.nullish.org/) before merging if you like.

### CODE REVIEW

**Comment by heavy-lifting** [comment]
Thank you! Learning so much about how git works too :)

**Comment by yaxu** [comment]
I tried swapping in the white-on-black logo (from
[Tidal Cycles Brand Guidelines (1).pdf](https://github.com/tidalclub/tidalclub.github.io/files/1405257/Tidal.Cycles.Brand.Guidelines.1.pdf))

I think it might look better but gets a bit cut off on the left hand side..

**Comment by yaxu** [comment]
I found the self-hosted webstats thingie and added the tracking code, the interface is on http://stats.lurk.org/ , I can share the password next time we meet !

**Comment by nullish** [comment]
Righto, did you scrap the Google Analytics snippet? I'll kill the account
we're using the self hosted thingy.

**Comment by yaxu** [comment]
Ah no I didn't spot it
(I use google analytics for my things but know others in tidal community have feelings against)

**Comment by nullish** [comment]
No worries, I can sort. On mobile at the mo. Yeah, that's fine, and ought
to be respected, especially if we want more clubs and contributors.

**Pull request merged**
